# Generated by Django 4.1.4 on 2022-12-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteshonors',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes_quotes', to='author.profile'),
        ),
    ]
