# Generated by Django 4.1.5 on 2023-01-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quoteshonors_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteshonors',
            name='char',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
