# Generated by Django 4.1.5 on 2023-01-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quoteshonors_char'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteshonors',
            name='char',
        ),
    ]
