# Generated by Django 4.1.5 on 2023-01-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('quotes', '0006_remove_quoteshonors_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='quotes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_comment', to='quotes.quoteshonors'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='author.profile'),
        ),
    ]
