# Generated by Django 4.1.5 on 2023-01-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
    ]
