# Generated by Django 4.1.1 on 2023-01-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_profile_image'),
        ('quotes', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteshonors',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_author', to='author.profile'),
        ),
        migrations.AlterField(
            model_name='quoteshonors',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_editor', to='author.profile'),
        ),
    ]
